name: CSBC bot news poster
run-name: ${{ github.actor }} start deployment 🚀
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    deploy_production:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: github.ref == 'refs/heads/master'
        steps:
            - name: connect to server
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                script: bash ~/csbc_selection_commite_bot/build.sh production